# liste contenant les capitales
liste_capitales = ['Kaboul', 'Pretoria', 'Tirana', 'Alger', 'Berlin', 'Andorre-la-Vieille', 'Luanda', "Saint John's",
                   'Riyad', 'Buenos Aires', 'Erevan', 'Canberra', 'Vienne', 'Bakou', 'Nassau', 'Manama', 'Dacca',
                   'Bridgetown', 'Minsk', 'Bruxelles', 'Belmopan', 'Porto-Novo', 'Thimbu', 'Sucre', 'Sarajevo',
                   'Gaborone', 'Brasilia', 'Bandar Seri Begawan', 'Sofia', 'Ouagadougou', 'Bujumbura', 'Praia',
                   'Phnom Penh', 'Yaoundé', 'Ottawa', 'Santiago', 'Pékin', 'Nicosie', 'Bogota', 'Moroni',
                   'Brazzaville', 'Kinshasa', 'Séoul', 'Pyongyang', 'San José', 'Yamoussoukro', 'Zagreb',
                   'La Havane', 'Copenhague', 'Djibouti', 'Saint-Domingue', 'Roseau', 'Le Caire', 'San Salvador',
                   'Abu Dhabi', 'Quito', 'Asmara', 'Madrid', 'Tallinn', 'Mbabane', 'Washington', 'Addis-Abeba',
                   'Suva', 'Helsinki', 'Paris', 'Libreville', 'Banjul', 'Tbilissi', 'Accra', 'Athènes',
                   "Saint George's", 'Guatemala', 'Conakry', 'Malabo', 'Bissau', 'Georgetown', 'Port-au-Prince',
                   'Tegucigalpa', 'Budapest', 'New Delhi', 'Jakarta', 'Téhéran', 'Bagdad', 'Dublin', 'Reykjavik',
                   'Jérusalem', 'Rome', 'Kingston', 'Tokyo', 'Amman', 'Astana', 'Nairobi', 'Bichkek', 'Tarawa',
                   'Koweït', 'Vientiane', 'Maseru', 'Riga', 'Beyrouth', 'Monrovia', 'Tripoli', 'Vaduz', 'Vilnius',
                   'Luxembourg', 'Skopje', 'Antananarivo', 'Kuala Lumpur', 'Lilongwe', 'Malé', 'Bamako', 'La Valette',
                   'Rabat', 'Majuro', 'Port Louis', 'Nouakchott', 'Mexico', 'Palikir', 'Chisinau', 'Monaco',
                   'Oulan-Bator',
                   'Podgorica', 'Maputo', 'Naypyidaw', 'Windhoek', 'Yaren', 'Katmandou', 'Managua', 'Niamey', 'Abuja',
                   'Oslo', 'Wellington', 'Mascate', 'Kampala', 'Tachkent', 'Islamabad', 'Melekeok', 'Jérusalem-Est',
                   'Panama', 'Port Moresby', 'Asunción', 'Amsterdam', 'Lima', 'Manille', 'Varsovie', 'Lisbonne', 'Doha',
                   'Damas', 'Bangui', 'Bucarest', 'Londres', 'Moscou', 'Kigali', 'Basseterre', 'Saint-Marin', 'Vatican',
                   'Kingstown', 'Honiara', 'Apia', 'Sao Tomé', 'Dakar', 'Belgrade', 'Victoria', 'Freetown', 'Singapour',
                   'Bratislava', 'Ljubljana', 'Mogadiscio', 'Khartoum', 'Djouba', 'Sri Jayawardenapura', 'Stockholm',
                   'Berne', 'Paramaribo', 'Douchanbe', 'Taipei', 'Dodoma', "N'Djamena", 'Prague', 'Bangkok', 'Dili',
                   'Lomé',
                   'Nukualofa', 'Port of Spain', 'Tunis', 'Achgabat', 'Ankara', 'Fanafuti', 'Kiev', 'Montevideo',
                   'Port-Vila', 'Caracas', 'Hanoi', 'Sanaa', 'Lusaka', 'Harare']

# liste contenant les pays
liste_pays = ['Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne', 'Andorre', 'Angola',
              'Antigua-et-Barbuda',
              'Arabie saoudite', 'Argentine', 'Arménie', 'Australie', 'Autriche', 'Azerbaïdjan', 'Bahamas', 'Bahrein',
              'Bangladesh', 'Barbade', 'Bélarus', 'Belgique', 'Belize', 'Bénin', 'Bhoutan',
              'Bolivie(État plurinational de)',
              'Bosnie-Herzégovine', 'Botswana', 'Brésil', 'Brunéi Darussalam', 'Bulgarie', 'Burkina Faso',
              'Burundi', 'Cabo Verde', 'Cambodge', 'Cameroun', 'Canada', 'Chili', 'Chine', 'Chypre', 'Colombie',
              'Comores',
              'Congo', 'Congo(la République démocratique du)', 'Corée-Sud', 'Corée-Nord', 'Costa Rica', "Côte d'Ivoire",
              'Croatie', 'Cuba', 'Danemark', 'Djibouti', 'dominicaine(la République)', 'Dominique', 'Égypte',
              'El Salvador', 'Émirats arabes unis', 'Équateur', 'Érythrée', 'Espagne', 'Estonie', 'Eswatini',
              "États-Unis d'Amérique", 'Éthiopie', 'Fidji', 'Finlande', 'France', 'Gabon', 'Gambie', 'Géorgie', 'Ghana',
              'Grèce', 'Grenade', 'Guatemala', 'Guinée', 'Guinée équatoriale', 'Guinée-Bissau', 'Guyana', 'Haïti',
              'Honduras',
              'Hongrie', 'Inde', 'Indonésie', "Iran (République Islamique d')", 'Iraq', 'Irlande', 'Islande', 'Israël',
              'Italie', 'Jamaïque', 'Japon', 'Jordanie', 'Kazakhstan', 'Kenya', 'Kirghizistan', 'Kiribati', 'Koweït',
              'Lao (la République démocratique populaire)', 'Lesotho', 'Lettonie', 'Liban', 'Libéria', 'Libye',
              'Liechtenstein', 'Lituanie', 'Luxembourg', 'Macédoine du Nord', 'Madagascar', 'Malaisie', 'Malawi',
              'Maldives',
              'Mali', 'Malte', 'Maroc', 'Marshall (les Îles)', 'Maurice', 'Mauritanie', 'Mexique',
              'Micronésie (États fédérés de)', 'Moldavie (la République de)', 'Monaco', 'Mongolie', 'Monténégro',
              'Mozambique', 'Myanmar', 'Namibie', 'Nauru', 'Népal', 'Nicaragua', 'Niger', 'Nigéria', 'Norvège',
              'Nouvelle-Zélande', 'Oman', 'Ouganda', 'Ouzbékistan', 'Pakistan', 'Palaos', 'Palestine, État de',
              'Panama',
              'Papouasie-Nouvelle-Guinée', 'Paraguay', 'Pays-Bas', 'Pérou', 'Philippines', 'Pologne', 'Portugal',
              'Qatar',
              'République arabe syrienne', 'République centrAfriqueine', 'Roumanie',
              "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", 'Russie (la Fédération de)', 'Rwanda',
              'Saint-Kitts-et-Nevis', 'Saint-Marin', 'Saint-Siège', 'Saint-Vincent-et-les Grenadines',
              'Salomon (les Îles)',
              'Samoa', 'Sao Tomé-et-Principe', 'Sénégal', 'Serbie', 'Seychelles', 'Sierra Leone', 'Singapour',
              'Slovaquie',
              'Slovénie', 'Somalie', 'Soudan', 'Soudan du Sud', 'Sri Lanka', 'Suède', 'Suisse', 'Suriname',
              'Tadjikistan',
              'Taïwan (Province de Chine)', 'Tanzanie (la République-Unie de)', 'Tchad', 'Tchéquie', 'Thaïlande',
              'Timor-Leste', 'Togo', 'Tonga', 'Trinité-et-Tobago', 'Tunisie', 'Turkménistan', 'Turquie', 'Tuvalu',
              'Ukraine',
              'Uruguay', 'Vanuatu', 'Venezuela (République bolivarienne du)', 'Viet Nam', 'Yémen', 'Zambie', 'Zimbabwe']

# dictionnaire contenant les meilleures pointages
meilleurs_pointages = {"Albert Einstein": 8, "Isaac Newton": 6, "Mike Tyson": 0, "Elon Musk": 3, "Stephen Hawking": 5}

